### ISSUE TITLE
Stream to HA Assist Pipeline

### ISSUE THREAD

**Issue by bendikrb** [rhasspy/rhasspy3#15]
I'm a bit lost -- I have installed the rhasspy3 hassio addon, which isn't quite usable yet as far as I can tell..
And if it was, I still wouldn't get to where I want, which is this;
1. Do wake on rpi satellite
2. Stream audio to home assistant server (I want to do stt using a cloud service or local wyoming whisper server).
3. Stream TTS audio back to the satellite.

This could be accomplished by doing what the existing [remote/websocket](https://github.com/rhasspy/rhasspy3/blob/master/programs/remote/websocket/bin/stream2stream.py) does, except against [HA`s WebSocket API](https://developers.home-assistant.io/docs/voice/pipelines/).

I have to assume I'm kicking in open doors here - but after reading around both here and there, I couldn't find any mention about this..

**Comment by bendikrb** [comment]
Never mind - I just discovered https://github.com/synesthesiam/homeassistant-pipeline/blob/master/audio_to_audio.py
Thanks :)

**Comment by bendikrb** [comment]
.. it just needs a little tweak to read audio like the websocket program does, not from stdin..

**Comment by WarLL3** [comment]
may you explain how you realised this setup?

**Comment by benbender** [comment]
@bendikrb would you mind to share your process and config? Would be gorgeous! <3

**Comment by lightsabata** [comment]
@bendikrb i'm also interested how you manage to make it work

**Comment by bendikrb** [comment]
I didn't, actually.
However, I'm encouraged to give it another try now that I see the latest commits to the [wyoming-v1 branch](https://github.com/rhasspy/rhasspy3/tree/wyoming-v1) + the pending pull requests from [@Shulyaka](https://github.com/rhasspy/rhasspy3/pulls/Shulyaka)

**Comment by benbender** [comment]
@bendikrb would love to see a working implementation!

**Comment by lightsabata** [comment]
with your advice i was able to make it work with the following method:

Download [https://github.com/rhasspy/rhasspy3/tree/wyoming-v1](url)

After configuring with the tutorial with your needs, you must install the program/remote/home_assistant 
```
mkdir -p config/programs/remote/
cp -R programs/remote/home_assistant config/programs/remote/
config/programs/remote/home_assistant/script/setup
```
the edit your configuration (here's mine):
```
programs:
  mic:
    arecord:
      command: |
        arecord -q -r 16000 -c 1 -f S16_LE -t raw -
      adapter: |
        mic_adapter_raw.py --rate 16000 --width 2 --channels 1
  wake:
    <YOUR_PREFERED_WAKE_WORD_PROGRAM:
  snd:
    aplay:
      command: |
        aplay --device rhasspy -q -r 22050 -f S16_LE -c 1 -t raw
      adapter: |
        snd_adapter_raw.py --rate 22050 --width 2 --channels 1
  remote:
    home_assistant:
      command: |
        bin/assist_pipeline.py --token "${token}" --server "${server}"
      template_args:
        token: "<YOUR_LIVE_LONG_ACCESS_TOKEN>"
        server: "<YOUR_HOME_ASSISTANT_URI:PORT>"

satellites:
  default:
    mic:
      name: arecord
    wake:
      name: <YOUR_PREFERED_WAKE_WORD_PROGRAM>
    remote:
      name: home_assistant
    snd:
      name: aplay
```
Make sure to have piper and whisper on home assistant correctly configure  (settings must be the same betwen add-ons configuration and vocal assistant setting in home assistant.

then you can run the following command to start listening on the rhasspy3 folder:
```
script/run bin/satellite_run.py --debug --loop
```

there is must be other and nicer ways to make it work and i would love to improve this

**Comment by synesthesiam** [comment]
Sorry everyone for all of the hacks needed to get things running :/
I'm heavily focused on wake word stuff for Home Assistant at the moment, but I will return to get things cleaned up in Rhasspy soon.

**Comment by Shulyaka** [comment]
This is a very early developer preview, so don't worry about that!

**Comment by lightsabata** [comment]
i agree with Shulyaka. 
I've just testing with nabu casa assistant cloud. it is pretty rock solid and at this state it work better than any voice assisant that i know so far! (speed, accuracy, customization) you've definitely earn my subscription !
By the way is there a method to output a sound after a wake word triggering ? (perhaps i'm a little too impatient)

**Comment by Shulyaka** [comment]
> By the way is there a method to output a sound after a wake word triggering ?

Try this:
```yaml
pipelines:
  default:
    wake:
      name: porcupine1
      after:
        command: |
          aplay activation.wav
```

**Comment by lightsabata** [comment]
Thanks, unfortunately it doesn't seems to work on my config

**Comment by Shulyaka** [comment]
Replace `activation.wav` with the path to the actual file you want to play. Also, it's not a full pipeline, just the important parts.

**Comment by lightsabata** [comment]
yes, i've also try with the full command (same as snd program) without success:

```
satellites:
  default:
    mic:
      name: arecord
    wake:
      name: porcupine2
      after: 
        command: |
          aplay --device rhasspy -q -r 22050 -f S16_LE -c 1 -t raw "${data_dir}/wake_alfred.wav"
    remote:
      name: home_assistant
    snd:
      name: aplay
```
