### ISSUE TITLE
"Illegal Instruction" encountered trying to start wyoming-whisper

### ISSUE THREAD

**Issue by bhoogter** [rhasspy/rhasspy3#21]
Apologies if this is not the forum or if it is answered elsewhere..  But, just trying to pull someone else's docker compose with `wyoming-whisper` in it, and encountering a python error on startup:

> /run.sh: line 5:     7 Illegal instruction     python3 -m wyoming_faster_whisper --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data "$@"

I'm assuming it's because of the underlying system Docker is running on?  An old MSI desktop with an AMD 64 cpu running Win10 and Docker Community.

Any help, or starting points to getting the container running?

Docker compose file is largely pulled from somewhere else, and I doubt is the cause.

```yaml
version: "3.9"
services:
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    ports:
      - '10200:10200'
    volumes:
      - '/media/storage/piper/data:/data'
    command: --voice en-gb-southern_english_female-low
   
  whisper:
   container_name: whisper
   image: rhasspy/wyoming-whisper
   ports:
     - '10300:10300'
   volumes:
     - '/media/storage/whisper/data:/data'
   command: --model tiny-int8 --language en
```
