### ISSUE TITLE
Confusing line in configuration.yaml in tutorial

### ISSUE THREAD

**Issue by KotBayun69** [rhasspy/rhasspy3#23]
There is a part in the tutorial where  `faster-whisper` is set up
```
asr:
    faster-whisper: ...
    faster-whisper.client:
      command: |
        client_unix_socket.py var/run/faster-whisper.socket
```
The second line is confusing (at least for me). I was assuming I should keep previous created entry for`faster-whisper: ...`  and add another for `faster-whisper.client`. Which apparently was wrong.

another issue I have had is in `piper` setup.
```
template_args:
        model: "${data_dir}/en-us-blizzard_lessac-medium.onnx"
```
I don't know why, but my file name was different: `en-us-lessac-low.onnx` . I spend some time trying to understand why am I getting an error when running the script
