### ISSUE TITLE
Outputting sound after wake word (satellite)

### ISSUE THREAD

**Issue by lightsabata** [rhasspy/rhasspy3#47]
Hi everyone !
i've managed to config a satellite connected to my home assistant server, it work like a charm but i would like to enhance my experience with a sound after triggering the wake word program.
ive tried to add a command on my configuration with no luck.

Is anybody knows a tweak to do this ?

Here's my satellite configuration:

```
satellites:
  default:
    mic:
      name: arecord
    wake:
      name: porcupine2
      after: 
        command: |
          aplay "${data_dir}/wake_alfred.wav"
    remote:
      name: home_assistant
    snd:
      name: aplay
```
Thanks
