### ISSUE TITLE
Pipeline that sends a feeback message after the wake word

### ISSUE THREAD

**Issue by jevylux** [rhasspy/rhasspy3#57]
Hi, I used the old rhasspy 2.5 and liked the fact that after detecting the wake word, i got an audio feedback.
I would like to see this feature in the test pipeline. I am not yet understanding everything enough to implement it by myself. 
So the objectif would be to have a pipeline that between the wake word and the intent handling, would send an audio feddback, in form of a preregistered wave file.
The best of all worlds would be ta have a tutorial about to achieve this.

**Comment by vshtykhnov** [comment]
it will help you  - Outputting sound after wake word (satellite) #47

**Updates:**
```
pipelines:
  default:
    wake:
      name: porcupine1
      after:
        command: |
          aplay activation.wav
```
